### ISSUE TITLE
undefined local variable or method `originalsourceid'

### ISSUE THREAD

**Issue by JPrevost** [scotdalton/exlibris-primo#11]
I'm not sure if you recall this bit of code, but if I comment out this line it works for me. 

https://github.com/JPrevost/exlibris-primo/commit/5fc074257b1defdc05d251fe1ba859f620b45aab

If I leave it, I get errors when I call #holdings on some records (but others work fine).
`*** NameError Exception: undefined local variable or method `originalsourceid' for #<Exlibris::Primo::Record:0x007fefbd5e9b60>`

If you have any ideas on how I may be able to safely fix this bug (without breaking things for others) I'd be happy to submit a pull. If not, I'll likely leave it commented out on a fork and use the forked gem in our project.

**Comment by scotdalton** [comment]
Will definitely look into it. I think I was enamored with `method_missing` when I wrote this, so that's probably the source of the bug.  Sorry about that.  Can you show the PNX for a record that works and for one that doesn't?  That could be the start of a test.

**Comment by JPrevost** [comment]
Thanks for the quick reply. I'll attach some PNX records tomorrow to hopefully help track down what's going on.

And yeah, `missing_method` gets used a lot in this gem :)

**Comment by JPrevost** [comment]
Sorry I haven't communicated on this in two weeks. I'll be able to get back to it soon...
